# Применение JWT

POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "buba",
    "password": "buba"
}


###
# Применение JWT - получение токена

POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "buba",
    "password": "buba"
}


### Получение токена

POST http://127.0.0.1:8000/api-token-auth/
Content-Type: application/json

{
    "username": "renzhin",
    "password": "1"
} 

###

# пример GET запроса

GET http://127.0.0.1:8000/cats/

###
#пример GET запроса с JWT-токеном
GET http://127.0.0.1:8000/cats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk1MzY0OTMwLCJqdGkiOiI2M2MyZDk3YTJjNWU0ZDg5OWUzYjM5NjYxODFhYzZiOSIsInVzZXJfaWQiOjN9.9i0QyGjEmWwNKKR2v-2MxoBnL3a5VUD4rcBrIppos20

###
#пример GET запроса с токеном
GET http://127.0.0.1:8000/cats/
Authorization: Token ac54823c56a67e1ae7f50af26fc3319e306bac84


###
GET http://127.0.0.1:8000/cats/1/

###

POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Goga3",
    "color": "Grey",
    "birth_year": 2022,
    "owner": 1
} 

###
# Добавляем котика с HEX-овым цветом.
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Хёксик",
    "color": "Black",
    "birth_year": 2022,
    "owner": 1
} 


###
# Запрос на добавление кота с хозяином
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

{
    "name": "Барсик",
    "color": "White",
    "birth_year": 2017,
    "owner": 1,
    "achievements": [
        {"name": "поймал мышку"},
        {"name": "разбил вазу"}
    ]
} 

###
# Запрос на добавление оунера
POST http://127.0.0.1:8000/owners/
Content-Type: application/json

{
    "first_name": "Hugo",
    "last_name": "Basckerwill"
} 

###
# ЗАгружаем пакетно, если serializer = CatSerializer(data=request.data, many=True)
POST http://127.0.0.1:8000/cats/
Content-Type: application/json

[
    {
        "name": "Стёп2",
        "color": "белый",
        "birth_year": 1971
    },
    {
        "name": "Мурка2",
        "color": "рыжий",
        "birth_year": 2010
    },
    {
        "name": "Пушок2",
        "color": "чёрный",
        "birth_year": 2018
    }
] 

###
# работаем с обновлением объекта через cat_update
POST http://127.0.0.1:8000/cat_update/1/
Content-Type: application/json

{
    "name": "Pushok",
    "color": "WhiteHouse",
    "birth_year": 2019
} 

###
# работаем с обновлением объекта через cat_patch
PATCH http://127.0.0.1:8000/cats/1/
Content-Type: application/json

{
    "color": "WhiteBlack"
} 